export const images = {
  heart: require('./images/heart.png'),
  doctor: require('./images/doctor.png'),
  medicine: require('./images/medicine.png'),
  ambulance: require('./images/ambulance.png'),
  prescription: require('./images/prescription.png'),
  profileDoctor: require('./images/profileDoctor.png'),
  food: require('./images/food.jpg'),
  anotherDoctor: require('./images/anotherDoctor.jpg'),
  covid19: require('./images/covid19.jpg'),
  diet: require('./images/diet.jpeg'),
  people: require('./images/people.jpg'),
  profilePic: require('./images/profilePic.jpg'),
  codeImage: require('./images/code-image.png'),
  sportsImage: require('./images/sports-image.jpg'),
  codingImage: require('./images/coding-image.jpg'),
  ngoImage: require('./images/ngo-image.png'),
  flash: require('./images/flash.jpg'),
  ironMan: require('./images/iron-man.jpg'),
  oliver: require('./images/oliver-queen.jpg'),
  virat: require('./images/virat-kohli.jpg'),
  ana: require('./images/ana.jpg'),
  janhvi: require('./images/jahnvi.jpg'),
  disha: require('./images/disha.jpg'),
};

export const icons = {
  email: require('./icons/email.png'),
  name: require('./icons/name.png'),
  password: require('./icons/password.png'),
  home: require('./icons/home.png'),
  message: require('./icons/message.png'),
  appointment: require('./icons/appointment.png'),
  profileBottom: require('./icons/profileBottom.png'),
  notification: require('./icons/notification.png'),
  search: require('./icons/search.png'),
  cross: require('./icons/cross.png'),
  back: require('./icons/back.png'),
  dots: require('./icons/dots.png'),
  chat: require('./icons/chat.png'),
  time: require('./icons/clock.png'),
  camera: require('./icons/camera.png'),
  heart: require('./icons/heart.png'),
  calories: require('./icons/calories.png'),
  weight: require('./icons/weight.png'),
  saved: require('./icons/saved.png'),
  app: require('./icons/app.png'),
  paymentMethod: require('./icons/payment-method.png'),
  faq: require('./icons/faq.png'),
  help: require('./icons/help.png'),
  go:require('./icons/go.png')
};

export const fonts = {
  poppinsRegular: 'Poppins-Regular',
  poppinsMedium: 'Poppins-Medium',
  poppinsSemiBold: 'Poppins-SemiBold',
  poppinsBold: 'Poppins-Bold',
  poppinsExtraBold: 'Poppins-ExtraBold',
};
